# Generated by Django 6.0 on 2025-12-30 23:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_customuser_is_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_verified",
        ),
    ]
