# Generated by Django 6.0 on 2026-01-03 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meeting", "0003_question_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="duration",
            field=models.IntegerField(
                default=60,
                help_text="The duration of the meeting in minutes",
                validators=[
                    django.core.validators.MaxValueValidator(60),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
