"""
Django settings for collaboard project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from django.http import HttpRequest
from dotenv import load_dotenv

load_dotenv()  # load all env variables


def get_env_var(env_var: str) -> str:
    """
    Gets a specific environment variable from a `.env` file
    :param env_var: Name of the environment variable to retrieve
    :return: Value of the requested environment variable
    """
    value = os.getenv(env_var)
    if value is None:
        error_message = f"Set the {env_var} environment variable!"
        raise ImproperlyConfigured(error_message)
    return value


ENV_TYPE_STR: str = get_env_var(
    "IS_DEV_ENV"
)  # controls the settings.py configuration depending on if it's dev or prod
if ENV_TYPE_STR.lower() in ["true", "1", "yes"]:
    IS_DEV_ENV: bool = True
else:
    IS_DEV_ENV: bool = False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR: Path = (
    Path(__file__).resolve().parent.parent
)  # Root = `collaboard folder root`


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY: str = get_env_var("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG: bool = IS_DEV_ENV

if IS_DEV_ENV:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
else:
    # TODO: Add Hosting VPS IP In Here
    ALLOWED_HOSTS = ["collaboard.site", "www.collaboard.site", "localhost"]


# Application definition

PROJECT_APPS = ["applications.authentication", "applications.meeting"]
EXTRA_DEPENDENCY_APPS = ["django_browser_reload"]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    *PROJECT_APPS,
]
if IS_DEV_ENV:
    INSTALLED_APPS.extend(EXTRA_DEPENDENCY_APPS)

EXTRA_DEPENDENCY_MIDDLEWARE = [
    "django_ratelimit.middleware.RatelimitMiddleware",
]
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",  # Custom middleware for django-browser-reload
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    *EXTRA_DEPENDENCY_MIDDLEWARE,
]

# Session definition
SESSION_ENGINE = (
    "django.contrib.sessions.backends.db"  # Store the session in the Database
)
SESSION_COOKIE_AGE: int = (
    60 * 60 * 24 * 7 * 2
)  # Cookie length stored in seconds (2 Weeks Here)
SESSION_COOKIE_HTTPONLY: bool = True
SESSION_COOKIE_NAME: str = "sessionid"
SESSION_COOKIE_SAMESITE: str = "Lax"

if not IS_DEV_ENV:
    SESSION_COOKIE_SECURE: bool = True
    USE_X_FORWARDED_HOST = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    CSRF_TRUSTED_ORIGINS = [
        "https://collaboard.site",
        "https://www.collaboard.site",
    ]

    def get_client_ip(request: HttpRequest) -> str:
        """
        Gets the clients exact IP address
        :param request: Request object of HttpRequest
        :return: The client's IP address
        """
        return request.META.get("HTTP_X_FORWARDED_FOR", "").split(",")[0].strip()

    RATELIMIT_IP_META_KEY = get_client_ip
    RATELIMIT_USE_CACHE = "default"

# Redirect definition
# TODO: Uncomment these later and delete this comment
LOGIN_URL: str = "login"
LOGOUT_REDIRECT_URL: str = "landing"

# Email definition (working via django-sendgrid package)
SENDGRID_API_KEY = get_env_var("SENDGRID_API_KEY")
EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"
DEFAULT_FROM_EMAIL = get_env_var("EMAIL_FROM_USER")
EMAIL_FROM_USER = get_env_var("EMAIL_FROM_USER")

# SendGrid settings
SENDGRID_SANDBOX_MODE_IN_DEBUG = (
    False  # False if you want to allow sending emails in development mode,
)
# True if you don't
SENDGRID_TRACK_EMAIL_OPENS = True
SENDGRID_TRACK_CLICKS_HTML = True
SENDGRID_TRACK_CLICKS_PLAIN = True

ROOT_URLCONF = "collaboard.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",  # root templates folder
        ],
        "APP_DIRS": True,  # also look in app directories
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "collaboard.wsgi.application"

# #TODO: `django-channels` config, make sure to uncomment when channels is ready and installed
# ASGI_APPLICATION = "collaboard.asgi.application"
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [("127.0.0.1", 6379)],  # Database 0
#         },
#     },
# }

# Logging definition
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)  # makes the logs directory if it doesn't exist yet

LOG_FILES = [
    "django.log",
    "authentication.log",
    "meeting.log",
]  # Add more log files here as needed

# creates all log files that don't exist yet
for log_file in LOG_FILES:
    log_file_path = LOGS_DIR / log_file
    log_file_path.touch(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
            "format": "%(levelname)s %(asctime)s %(name)s %(funcName)s %(lineno)d %(message)s",
        },
        "verbose": {  # keep for local dev
            "format": "{levelname:<8} {asctime} | {name}:{funcName}:{lineno} - {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "django": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "django.log",
            "formatter": "verbose",
            "maxBytes": 10485760,  # 10MB
            "backupCount": 3,
        },
        "authentication": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "authentication.log",
            "formatter": "json",
            "maxBytes": 10485760,  # 10MB
            "backupCount": 3,
        },
        "meeting": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "main.log",
            "formatter": "json",
            "maxBytes": 10485760,  # 10MB
            "backupCount": 3,
        },
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["django", "console"],
            "level": "INFO",
            "propagate": True,
        },
        "applications.authentication": {
            "handlers": ["authentication", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "applications.meeting": {
            "handlers": ["meeting", "console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": get_env_var("DB_NAME"),
        "USER": get_env_var("DB_USER"),
        "PASSWORD": get_env_var("DB_PASSWORD"),
        "HOST": get_env_var("DB_HOST"),
        "PORT": get_env_var("DB_PORT"),
    }
}

CACHES = {  # configured alongside `django-redis` package
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",  # server port/location
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 100,
                "retry_on_timeout": True,
            },
        },
    }
}


# Custom User Model
AUTH_USER_MODEL = "authentication.CustomUser"

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Media file definition
MEDIA_URL = "/media/"
MEDIA_ROOT = "/home/ubuntu/collaboard-inc/mediafiles/"  # must match project folder name

# Static file definition
STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static"  # global static folder
]
STATIC_ROOT = (
    "/home/ubuntu/collaboard-inc/staticfiles/"  # for production (via collectstatic)
)
